version: '3.8'

services:
  blog-spring:
    container_name: blog-spring
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BLOG_SPRING_PORT}:${BLOG_SPRING_PORT}"
    environment:
      PORT: ${BLOG_SPRING_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - postgres
    networks:
      - mynetwork



  postgres:
    image: postgres:14-alpine
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${LOCALHOST_PGADMIN_PORT}:${PGADMIN_PORT}
    depends_on:
      - postgres
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
